server:
  port: ${SERVER_PORT:8080}
  shutdown: graceful
  forward-headers-strategy: framework
  error:
    whitelabel:
      enabled: false
  compression:
    enabled: true
    mime-types:
      - application/json
      - application/xml
      - text/html
      - text/xml
      - text/plain
spring:
  application:
    name: api-onboarding-dis
  profiles:
    active: ${ENV_PROFILE:local}
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/transfer}
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USER_NAME:root}
    password: ${DATABASE_USER_PASSWORD:root}
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      database-plataform: org.hibernate.dialect.PostgreSQLDialect

client:
  authorization-mock:
    url: https://run.mocky.io/v3/8997a273-ec48-4289-a1df-ecb95bad6e51
  notification-mock:
    url: https://run.mocky.io/v3/54dc2cf1-3add-45b5-b5a9-6bf7e7f1f4a6